### ISSUE TITLE
v1: all tags list all posts

### ISSUE THREAD

**Issue by igalic** [Dalgona/Serum#177]
I have a blog https://igalic.co/thoughts/
the source is here: https://codeberg.org/meena-co/website/src/branch/main/thoughts

When clicking on any of the several tags, for example, [talk](https://igalic.co/tags/talk/) which only appears once, all 4 articles show up

That strikes me likea bug.

**Comment by Dalgona** [comment]
Your template (`list.html.eex`) should look like this:

```diff
@@ -1,7 +1,7 @@ list.html.eex
 <section>
     <p>[redacted]<p>
     <ul id="posts">
-    <%=  for x <- @all_posts do %>
+    <%= for x <- @page[:posts] do %>
         <%=  unless x.extras["draft"] == "true" do %>
         <li>
             <h3><a href="<%= x.url %>"><%= x.title %></h3>
```

By definition, `@all_posts` variable holds literally _all_ blog posts. In `list.html.eex`, the page-specific variable `@page[:posts]` should be used in order to get an appropriate list of blog posts, depending on a tag or a page number(if pagination is enabled). [(Documentation)](https://dalgona.github.io/Serum/docs/templates.html#@page---current-page)

**Comment by igalic** [comment]
thank you, very much! 

that must've been a bad copy/paste after thoroughly destroying that template to restore it to a working state
