### ISSUE TITLE
Why the strict post header datetime format?

### ISSUE THREAD

**Issue by dragsubil** [Dalgona/Serum#18]
Hello!

In the docs, you've specified that the date format for posts should be `YYYY-MM-DD hh:mm:ss`. 
Is it possible to optionally write just `YYYY-MM-DD` for date? Why the need for writing time also?

I really like Serum by the way. It's great!

**Comment by Dalgona** [comment]
Hey, thanks for your feedback. 😄 

Actually, there's no special reason why I made it so (maybe because I'm the only one who develops/maintains this project?), and of course, I can  loosen the constraint. But please be aware that it may take several days because I'm currently busy doing some school things.

**Comment by dragsubil** [comment]
Maybe I can help out and send a pull request? 
>  But please be aware that it may take several days because I'm currently busy doing some school things.

Take as long as you like! There's no rush.

**Comment by Dalgona** [comment]
Closed by PR #19. Thanks again!
