### ISSUE TITLE
Attaching theme

### ISSUE THREAD

**Issue by djKooks** [Dalgona/Serum#21]
Hello.
I'm currently working on some blogs with `jekyll` and `hexo`, and thought about it would be good if it can attach variable theme with certain way(though there is theme, but people could work on it if there is a process to do it).
Do you have a plan for this, or it is not fit on your concept?

Thanks.

**Comment by Dalgona** [comment]
Support for themes is the most requested feature so far. Yes, I definitely have a plan for this, and I will start working on it as soon as I get some huge things done. :laugh:

**Comment by Dalgona** [comment]
Honestly, I could not maintain this project for about a year, due to campus schedules and loss of motivation, and so on. But I never abandoned this project, so I was a little bit sad when I saw this issue has been silently closed.

Now, I'm happy to say that I'm ready to implement the "themes" feature. The inner structure of the code base has changed and improved a lot, compared to then, so adding new awesome features to this project is a lot more affordable. I still can't say that themes will be available before v1.0.0, but I'm sure this won't take another two or three years.

**Comment by Dalgona** [comment]
I have developed a document about Serum themes: https://github.com/Dalgona/Serum/wiki/Themes

I'll start working on themes on a separate branch, based on this document. :rocket:

**Comment by Dalgona** [comment]
The long-awaited theme feature is almost ready to roll out! The `wip/themes` branch will be merged after some more tests and refactoring, and finally this will be included in v1.1.0 release.

This [video (link to a tweet)](https://twitter.com/d57pub_/status/1126448642259185664) is a sneak peak of how Serum themes work. Check it out!

**Comment by dsignr** [comment]
Thanks for your hard work. Thank you for keeping this project alive. We REALLY need this in the Elixir eco-system!

**Comment by Dalgona** [comment]
I think I can close this issue now. Support for themes will be included in the v1.1.0 release. Also, the `serum_new` Hex package will provide another global Mix task, `serum.new.theme`, which helps you create a new Serum theme project.
