### ISSUE TITLE
Generating post via command line

### ISSUE THREAD

**Issue by djKooks** [Dalgona/Serum#22]
How about make a command option for generating new post, like `serum new ABC`?
If you have plan but not working on yet, I'll try on it.

Thanks.

**Comment by Dalgona** [comment]
Thank you for your suggestion. Actually, I've been working on the feature you're talking about since the last month. I'm planning two new Serum tasks, which are:

- `serum newpage <page-title> [options ...]`

    Creates a new file under `pages/` directory. The first argument becomes the title of the new page. Some additional options will be provided for the end-user to set its group, order, type (`md`, `html`, `html.eex`), etc.

- `serum newpost <post-title> [options ...]`

   Creates a new file under `posts/` directory. The first argument will be the title of the new post. Date will be automatically set to the moment this command is run, but some options will also be provided to manually set the date and tags.

In both the two tasks, the header area (lines between two `===`s) will be automatically populated based on information the user provided, and the file name will be determined by the title (e.g. "Hello, world!" &rarr; `hello-world.md`), but I will also allow the users to override the default file name.

Please note that it will take several weeks for me to finish this up because I need to prepare for the mid-term exam. :joy: In the meantime, if you have any comments on my plan, please feel free to leave follow-up comments here :blush:

**Comment by djKooks** [comment]
@Dalgona Great! Just keep working when you're available. I'll think about some other points which can enhance this project.

**Comment by djKooks** [comment]
@Dalgona Or you could make a development branch for this, so other people could support your work. Thanks.

**Comment by Dalgona** [comment]
Yeah, all my works so far are stored in a separate branch. I will push this when I make some more progress. Thanks.

**Comment by Dalgona** [comment]
Whoa, long time has passed since then! I didn't forget about this project, but I had little time to take care of it. 😢 Here are some screenshots of the upcoming feature.

* Command Help

    ![screenshot_20180125_220630](https://user-images.githubusercontent.com/2667858/35389803-69e7656e-021c-11e8-884a-5949dba431d8.png)

* Running `serum newpage` task

    ![screenshot_20180125_220819](https://user-images.githubusercontent.com/2667858/35389805-6c8b5302-021c-11e8-804a-de2c2d426e2e.png)

* Generated page file

    ![screenshot_20180125_220959](https://user-images.githubusercontent.com/2667858/35389823-826e9d46-021c-11e8-9dba-2b0c696cacdc.png)

**Comment by Dalgona** [comment]
Recent snapshot provides `newpage` and `newpost` tasks. CD into your project directory and run `serum help` to check them out.
