### ISSUE TITLE
Cannot disable generation of "posts"

### ISSUE THREAD

**Issue by igalic** [Dalgona/Serum#40]
Currently the way to disable posts is to remove the `posts` directory, however, that doesn't disable the run of Posts' generator:

```
Loading post files...
 * Cannot access `posts/'. No post will be generated.
Compiling templates...
Processing page files...
Processing post files...
Generating post lists...
Generating fragments...
Generating complete HTML pages...
Several errors occurred from page_generator:
  ❌  /home/meena/src/co/website/templates/base.html.eex: key :label not found in: %{current_page: 1, images: [], max_page: 1, next_url: nil, posts: [], prev_url: nil, tag: nil, title: "All Posts", type: :list, url: "/posts/index.html"}
  ❌  /home/meena/src/co/website/templates/base.html.eex: key :label not found in: %{current_page: 1, images: [], max_page: 1, next_url: nil, posts: [], prev_url: nil, tag: nil, title: "All Posts", type: :list, url: "/posts/page-1.html"}
** (Mix) could not build the website due to above error(s)
```

This seems to be caused by my `templates/base.html.eex` using a field which doesn't occur in Posts:

```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title><%= @site.name %> - <%= @page.label %></title>
```

but how could it be? Posts aren't generated??
how did we get there?

i believe the error (and easy fix) is here:

https://github.com/Dalgona/Serum/blob/0aa3b5132847d8502875411e94b9aa1d8fa91dd0/lib/serum/build/file_processor.ex#L42-L44

when our posts map is empty, we should just do nothing!

**Comment by Dalgona** [comment]
Given your error log and codes, there is no problem with Serum's post generation functionality. But yes, a list of blog posts, which is obviously empty, is still generated. (Post generation and post list generation are two distinct functions of Serum.) I'll fix the code so that lists are not generated when there is no blog post.

By the way, the expression `@page.label` is valid only when `@page.type === :page`, i.e., when rendering pages in your `pages/` directory. Please be careful when using variables in `base.html.eex`, as some variables are not available in all situation.

You could rewrite the code like this:

```html
<%
title =
  if @page.type === :page do
    @page.label
  else
    @page.title # This is always valid.
  end
%>
...
<title><%= @site.name %> - <%= title %></title>
```

... or like this:

```html
<title><%= @site.name %> - <%= @page.label || @page.title %></title>
```

**Comment by igalic** [comment]
thank you very much for your quick response!

since i don't want to have posts, and only pages, i thought it was safe to use!

**Comment by Dalgona** [comment]
I truly understand. I should have noticed this case earlier... :sweat_drops:
